### PR TITLE
Fix script pre_translate.sh

### PR DESCRIPTION
**Pull request by adissadis**

### CODE REVIEW

**Comment by adissadis** [comment]
@timlinux hi Tim, could you check this PR? Like what you suggest in https://github.com/inasafe/inasafe-doc/pull/332 i comment those line and tried to run the script again. And i didn't see any error. So, i assume this script work without those line.

**Comment by timlinux** [comment]
Hi @adissadis 

It would be better if in this PR you made a branch which included only the changes to the scripts and not all the other tr updates.

**Comment by adissadis** [comment]
@timlinux do you mean i separate the scripts fix and tr update and push those branch into this PR?

**Comment by adissadis** [comment]
@timlinux i already made a branch in my repo (pre_transifex_merge) but i don't know how to push this branch to this PR

**Comment by timlinux** [comment]
@adissadis if you do (from your branch):

```
git push origin <branch name>
```
Then go to your GitHub fork on the web and make a pull request from there.

**Comment by adissadis** [comment]
@timlinux okay i already do it in https://github.com/inasafe/inasafe-doc/pull/335

so can i merge this Pull request?

**Pull request merged**
