### PR TITLE
Fix filename for QGIS training

### PR DESCRIPTION
**Pull request by adissadis**
I fix some filename in training material in order to get better file name.

Here's my file also (if needed):
https://drive.google.com/open?id=0Bxk-3mw_fhapV2xnTXF3ZXlaUGc

### CODE REVIEW

**Comment by timlinux** [comment]
LGTM

**Comment by timlinux** [comment]
Please let me know if staging.docs.inasafe.org updates correctly after you merge!

**Comment by adissadis** [comment]
i just updated user-doc installation document

**Comment by timlinux** [comment]
Thanks @adissadis 

By the way, it is better to make many small pull requests each fixing one thing if possible.

**Comment by adissadis** [comment]
Oh okay @timlinux. Next time i will create small pull request for each fixing. This PR will be merge now

**Pull request merged**
